apiVersion: v1
kind: Service
metadata:
 name: jenkins-instance-service
 labels:
 app: jenkins-instance
spec:
 type: LoadBalancer
 ports:
 - port: 9091
 targetPort: 5050
 protocol: TCP
 selector:
 app: jenkins-instance